name: Design practice meet - assets
description: Issue ticket to collect assets for your practice meet.
title:  "{Your Name}: {Practice area} Practice Meet - {Month}"
labels: [ ]
assignees:
  - octocat
body:
  - type: textarea
    id: title
    attributes:
      label: Talk title
      description:
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: name
    attributes:
      label: Your name
      description:
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: logistics
    attributes:
      label: Date, time, location
      description:
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: blurb
    attributes:
      label: Blurb
      description: One-sentence description of the session.  Example https://www.instagram.com/p/C_ODL_UJQ2L/
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: photo
    attributes:
      label: Blurb
      description: Please upload a photo of you.  It will be used in your flyer.  Example https://www.instagram.com/p/C_3CMvvtx2K/
      placeholder:
      value:
    validations:
      required: true